# -*- coding: utf-8 -*-
"""Plot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1njng5wlSxpRDnSht9qVptyBDniFMKvs0
"""

import numpy as np

niz = np.random.randint(low=1,high=100,size=100)

niz

#for x in niz: print(x)

pip install stem

import matplotlib.pyplot as plt

plt.stem(niz)

plt.hist(niz)

a = plt.hist(niz)

niz.mean()