# -*- coding: utf-8 -*-
"""Practice3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CMo1xZYCkQ8Pok3WOraRJzSDHhEDZ-Hc

# Vežba broj 3 - Uvod u NumPy
"""

import numpy as np

a=np.arange(15).reshape(3,5)

b=np.arange(4)

b

a

a.shape

a.ndim

a.dtype.name

a.itemsize #64/8 daje broj bajtova

a.size

a=np.array([2,3,4])

a

a.dtype

b=np.array([1.2,3.1,3])

b

b=np.array([[1.5,2,3],[4,5,6]])

b

c=np.array([[1,2],[3,4]],dtype=complex)

c

np.zeros((4,4))

np.ones((2,3,4))

np.ones((4,2))

np.ones((4,2), dtype=float)

np.empty((4,8)) #random

from numpy import pi

np.linspace(0,2,9) #prva i druga od do, poslednje je koliko brojeva će biti

"""Projekti su od 5-10, 20, 30 40+ poena u zavisnosti koliko nam fali za željenu ocenu"""

a[2:5]

import pandas as pd

s = pd.Series([1,3,5,np.nan,6,8])

s

dates = pd.date_range("20130101", periods=6)

dates

df=pd.DataFrame(np.random.randn(6,4), index = dates, columns = list("ABCD"))

df

df2=pd.DataFrame({"A":1.,
                  "B":pd.Timestamp("20190101"),
                  "C":pd.Series(1,index=list(range(4)),dtype="float32"),
                  "D":np.array([3]*4, dtype = "int32"),
                  "E":pd.Categorical(["test", "train", "test", "train"]),
                  "F":"foo"
                 })

df2

df2.dtypes

#Uvid u podatke iz DataFrame

df.index

df.columns

df.values

#sortiranje

df.sort_index(axis=1, ascending=False)



df.T